# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-4.4.1
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2023-02-22T20:57:53Z"
  labels:
    app: kafkapp
  name: kafkapp
spec:
  containers:
  - args:
    - /opt/bitnami/scripts/zookeeper/run.sh
    env:
    - name: ALLOW_ANONYMOUS_LOGIN
      value: "yes"
    image: docker.io/bitnami/zookeeper:latest
    name: zookeeper-server
    ports:
    - containerPort: 2181
      hostPort: 2181
    - containerPort: 9092
      hostPort: 9092
    resources: {}
    securityContext:
      runAsNonRoot: true
  - args:
    - /opt/bitnami/scripts/kafka/run.sh
    env:
    - name: KAFKA_BROKER_ID
      value: 1
    - name: KAFKA_CFG_ZOOKEEPER_CONNECT
      value: kafkapp-zookeeper-server:2181
    - name: KAFKA_ADVERTISED_HOST_NAME
      value: kafkapp-kafka-server
    - name: KAFKA_CFG_ADVERTISED_LISTENERS
      value: "PLAINTEXT://127.0.0.1:9092"
    - name: ALLOW_PLAINTEXT_LISTENER
      value: "yes"
    image: docker.io/bitnami/kafka:latest
    name: kafka-server
    resources: {}
    securityContext:
      runAsNonRoot: true
  - args:
    - postgres
    env:
    - name: POSTGRES_PASSWORD
      value: postgres
    image: docker.io/library/postgres:latest
    name: kafkadb
    ports:
    - containerPort: 5432
      hostPort: 5432
    resources: {}
    volumeMounts:
    - mountPath: /docker-entrypoint-initdb.d
      name: home-jgero-git-ticket-booking-db_init-host-0
  hostname: kafkapp
  restartPolicy: Always
  volumes:
  - hostPath:
      path: /home/jgero/git/ticket-booking/db_init
      type: Directory
    name: home-jgero-git-ticket-booking-db_init-host-0
status: {}

