# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-4.4.1
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2023-02-22T20:57:53Z"
  labels:
    app: kafkapp
  name: kafkapp
spec:
  containers:
  - args:
    - /opt/bitnami/scripts/zookeeper/run.sh
    env:
    - name: ALLOW_ANONYMOUS_LOGIN
      value: "yes"
    image: docker.io/bitnami/zookeeper:latest
    name: zookeeper-server
    ports:
    - containerPort: 2181
      hostPort: 2181
    - containerPort: 9092
      hostPort: 9092
    resources: {}
    securityContext:
      runAsNonRoot: true
  - args:
    - /opt/bitnami/scripts/kafka/run.sh
    env:
    - name: KAFKA_CFG_ZOOKEEPER_CONNECT
      value: 127.0.0.1:2181
    - name: KAFKA_CFG_ADVERTISED_LISTENERS
      value: "PLAINTEXT://127.0.0.1:9092"
    - name: ALLOW_PLAINTEXT_LISTENER
      value: "yes"
    image: docker.io/bitnami/kafka:latest
    name: kafka-server
    resources: {}
    securityContext:
      runAsNonRoot: true
  hostname: kafkapp
  restartPolicy: Never
status: {}

